name       : paperwork-gui
version    : 1.3.0
release    : 7
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/paperwork/-/archive/1.3.0/paperwork-1.3.0.tar.gz : 4070ffd21197a7e20ade035fb63e5448ea7ca1eb9a27d32098ec49108aaad23a
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Using scanners and OCR to grep paper documents the easy way
description: |
    Paperwork is a personal document manager. It manages scanned documents and PDFs. It iss designed to be easy and fast to use. The idea behind Paperwork is "scan & forget": You can just scan a new document and forget about it until the day you need it again. In other words, let the machine do most of the work for you.
builddeps  :
    - git
rundeps    :
    - libinsane
    - paperwork-backend
    - poppler
    - python-dateutil
    - python-distro
    - python-pyocr
    - python-six
    - pyxdg
build      : |
    %make
install    : |
    pushd paperwork-gtk
      %python3_install
    popd

    install -Dm00644 $pkgfiles/paperwork.desktop $installdir/usr/share/applications/paperwork.desktop
    install -Dm00644 $workdir/paperwork-gtk/data/paperwork.svg $installdir/usr/share/icons/hicolor/symbolic/apps/paperwork.svg
