name       : paperwork
version    : 2.0.3
release    : 12
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/paperwork/-/archive/2.0.3/paperwork-2.0.3.tar.gz : 7eeebb02bdd4d60eb95f47a1f48a1cde36de7c7efb8f46329dbb78e5ce8d31ec
    - https://download.openpaper.work/data/paperwork/master_b6d0a1ed/data.tar.gz : 3a3895fe6626d98f54f21a388a73a819792da51cc1908c7be819213e0a9baa8b
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Using scanners and OCR to grep paper documents the easy way
description: |
    Paperwork is a personal document manager. It manages scanned documents and PDFs. It is designed to be easy and fast to use. The idea behind Paperwork is "scan & forget": You can just scan a new document and forget about it until the day you need it again. In other words, let the machine do most of the work for you.
replaces:
    - paperwork-gui
builddeps  :
    - paperwork-backend
    - python-psutil
    - pyxdg
    - xdg-utils
    - xorg-server-xvfb
rundeps    :
    - paperwork-backend
    - python-dateutil
    - pyxdg
patterns   :
    - docs:
      - /usr/lib/python3.9/site-packages/paperwork_gtk/model/help/out/*.pdf
setup      : |
    %patch < $pkgfiles/00001-missing-version.patch paperwork-gtk/src/paperwork_gtk/_version.py
    tar xzvf $sources/data.tar.gz -C $workdir/
build      : |
    make l10n_compile
    %make
install    : |
    pushd paperwork-gtk
      %python3_install
    popd

    # install icons and desktop file
    export PYTHONPATH=%installroot%/usr/lib/python%python3_version%/site-packages:$PWD
    xvfb-run -a python3 -m paperwork_gtk.main install \
        --icon_base_dir=$installdir/usr/share/icons \
        --data_base_dir=$installdir/usr/share
