name       : paperwork
version    : 2.1.0
release    : 14
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/paperwork/-/archive/2.1.0/paperwork-2.1.0.tar.gz : ea49c0d3d0da2333a70e930fdbe4431ae91085fa1e2493868945329096eba1fa
    - https://download.openpaper.work/data/paperwork/testing_705a86cc/data.tar.gz : 337c255e07e087ac2028036532c0a6baaa9be6274a178baa36b5ae9f51540855
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Using scanners and OCR to grep paper documents the easy way
description: |
    Paperwork is a personal document manager. It manages scanned documents and PDFs. It is designed to be easy and fast to use. The idea behind Paperwork is "scan & forget": You can just scan a new document and forget about it until the day you need it again. In other words, let the machine do most of the work for you.
replaces   :
    - paperwork-gui
builddeps  :
    - pkgconfig(libhandy-1)
    - paperwork-backend
    - pyxdg
    - xdg-utils
    - xorg-server-xvfb
rundeps    :
    - libhandy
    - paperwork-backend
    - python-dateutil
    - pyxdg
patterns   :
    - docs :
        - /usr/lib/python3.9/site-packages/paperwork_gtk/model/help/out/*.pdf
setup      : |
    %patch < $pkgfiles/00001-missing-version.patch paperwork-gtk/src/paperwork_gtk/_version.py
    tar xzvf $sources/data.tar.gz -C $workdir/
build      : |
    make l10n_compile
    %make
install    : |
    pushd paperwork-gtk
      %python3_install
    popd

    # install icons and desktop file
    export PYTHONPATH=%installroot%/usr/lib/python%python3_version%/site-packages:$PWD
    xvfb-run -a python3 -m paperwork_gtk.main install \
        --icon_base_dir=$installdir/usr/share/icons \
        --data_base_dir=$installdir/usr/share
