name       : paperwork-gui
version    : 1.3.1
release    : 11
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/paperwork/-/archive/1.3.1/paperwork-1.3.1.tar.gz : 70a3b9faf8d5edcd54fa1dd8cb4f517d319a18efe9898fce3b9cb43b2564885a
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Using scanners and OCR to grep paper documents the easy way
description: |
    Paperwork is a personal document manager. It manages scanned documents and PDFs. It iss designed to be easy and fast to use. The idea behind Paperwork is "scan & forget": You can just scan a new document and forget about it until the day you need it again. In other words, let the machine do most of the work for you.
builddeps  :
    - git
rundeps    :
    - paperwork-backend
    - python-dateutil
    - python-six
    - pyxdg
build      : |
    %make
install    : |
    pushd paperwork-gtk
      %python3_install
    popd

    install -Dm00644 $pkgfiles/paperwork.desktop $installdir/usr/share/applications/paperwork.desktop
    install -Dm00644 $workdir/paperwork-gtk/data/paperwork.svg $installdir/usr/share/icons/hicolor/symbolic/apps/paperwork.svg
